name: Documentation

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  Generate_Documentation:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Project
        uses: actions/checkout@v3
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Checkout docs branch and hardsync with master
        run: |
          git checkout gh-pages 2>/dev/null || git checkout -b gh-pages
          git reset --hard master
      - name: Setup yarn
        run: |
          yarn install --immutable --immutable-cache --check-cache
      - name: Generate Documentation
        run: yarn docs
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          TIMESTAMP=`date +%s` 
          git add docs
          git commit --no-verify -m "Generated docs: $TIMESTAMP"
      - name: Push
        run: git push -f -u origin gh-pages --no-verify
