name: Stable Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Build_Docker_Image_on_new_Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Project
        uses: actions/checkout@v2
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: Build frontend
        run: |
          npm ci
          npm run-script build
          cp -r build webapp_provider/public
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      -
        name: Generate Image Tag from Git Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Push Image to DockerHub Registry
        run: |
          VERSION=${{ steps.vars.outputs.tag }}
          docker build -t filefighter/frontend:$VERSION -t filefighter/frontend:stable webapp_provider/
          docker push filefighter/frontend:$VERSION
          docker push filefighter/frontend:stable
