name: Storybook Release

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  Build_Docker_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Project
        uses: actions/checkout@v2
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Build storybook
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn run build-storybook
          cp -r storybook-static  storybook_provider/public
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      -
       name: Push Image to DockerHub Registry
       run: |
          VERSION=latest
          docker build -t filefighter/storybook:$VERSION storybook_provider/
          docker push filefighter/storybook:$VERSION
      - name: Trigger update on server
        run: |
          curl -u ${{ secrets.LOG_CREDS }} https://logs.filefighter.de/storybook-update-script.log
